fun main() {
    println("===================== Início ======================")
    println("===================== Exemplos de funções ======================")
    Functions().func()
    println("===================== Fim dasfunções ======================")
    println("===================== Strings ======================")
    ManipulandoStrings().str()
    println("===================== Fim Strings ======================")
    println("===================== Cálculos ======================")
    Math().calc()
    println("===================== Fim Cálculos ======================")
    println("===================== Condicionais ======================")
    Condicionais().conditionals(19)
    println("===================== Fim Condicionais ======================")
    println("===================== When ======================")
    ExempleWhen().Exemple(2)
    ExempleWhen().ExempleIn(50)
    println("===================== Fim When ======================")
    println("===================== ReadData ======================")
    ReadData().ReadInfo()
    println("===================== Fim ReadData ======================")
    println("===================== For ======================")
    ExempleFor().Exemple()
    println("===================== Fim For ======================")
    println("===================== While ======================")
    WhileExemple().Exemplewhile()
    println("===================== Fim While ======================")
    println("===================== Do While ======================")
    ExempleDoWhile().doExemple()
    println("===================== Fim Do While ======================")
    println("===================== Null ======================")
    NullPoinerKT().nullExemple()
    println("===================== Fim Do Null ======================")
    println("===================== Elvis ======================")
    Elvis().ExempleElvis()
    println("===================== Fim Do Null ======================")
    println("===================== Fim ======================")
}